name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode 12.4
      run: sudo xcode-select -s /Applications/Xcode_12.4.app
    - name: Generate xcodeproj
      run: swift package generate-xcodeproj
    - name: Show Schemes
      run: xcodebuild test -list
    - name: Show Destinations
      run: xcodebuild test -scheme 'Knob-Package' -showdestinations
    - name: Run Mac Tests
      run: xcodebuild test -scheme 'Knob-Package' -destination 'platform=macOS'
    - name: Run iOS Tests
      run: xcodebuild test -scheme 'Knob-Package' -destination 'name=iPhone 11'
