name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode 16.3
      run: sudo xcode-select -s /Applications/Xcode_16.3.app
    - name: Build, test, and code coverage
      run: make
    - name: Create Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_UPDATE }}
        gistID: b307c10e9eb7882e6a83a3bcb1e5cd5d
        filename: Knob-coverage.json
        label: Coverage
        message: ${{ env.PERCENTAGE }}
        color: success
