name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run Tests
      run: swift test -v --enable-code-coverage
    - name: Generat Test Coverage
      run: |
        set -x
        XCTEST_PATH="$(find . -name '*.xctest')"
        set -- $(xcrun llvm-cov report ${XCTEST_PATH}/Contents/MacOS/*PackageTests -instr-profile .build/debug/codecov/default.profdata -ignore-filename-regex='.build/|Tests/' | tail -1)
        echo "$4" > .build/debug/codecov/percentage.txt
        echo "PERCENTAGE=$4" >> $GITHUB_ENV
    - name: Create Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_UPDATE }}
        gistID: b307c10e9eb7882e6a83a3bcb1e5cd5d
        filename: Knob-coverage.json
        label: Coverage
        message: ${{ env.PERCENTAGE }}
        color: success
